### ISSUE TITLE
calling $request in RouteServiceProvider::boot()

### ISSUE THREAD

**Issue by Jimbolino** [mertyildiran/laraup#2]
```
$ cat app/filters.php
<?php

App::before(function (Illuminate\Http\Request $request) {
    $request->setTrustedProxies(['1.1.1.1']); // load balancer
});
```

will result in a syntax error in RouteServiceProvider.php:
```
    public function boot()
    {
        //
        $request->setTrustedProxies(['1.1.1.1']); // load balancer

        parent::boot();
    }
```

I think you can safely change `$request` in `request()`

**Comment by mertyildiran** [comment]
@Jimbolino added with https://github.com/mertyildiran/laraup/commit/5087903fda79c3f86373b2ef7890489fb01f980c

**Comment by javadiahad** [comment]
I get  In RouteServiceProvider.php line 40: syntax error, unexpected 'public' (T_PUBLIC)

generated RouteServiceProvider file looks like this 


 public function boot()
    {
        //
	{
		//

		//
        parent::boot();
	{
    }

I can manually fix it and continue running remaining script by commenting every line between line 45 and 140  but in the following every file will removed from new laravel 5.8 project ,I don't have idea about relation between  two issue 

[errorDetail.txt](https://github.com/mertyildiran/laraup/files/4019103/errorDetail.txt)

[RouteServiceProvider.php.txt](https://github.com/mertyildiran/laraup/files/4019105/RouteServiceProvider.php.txt)

**Comment by mertyildiran** [comment]
@javadiahad this is not a perfectly generalised solution to upgrade a Laravel project from 4.2 to 5.8. Because there is no such solution. In fact, you should fork this repo and customize it according to your needs.
